config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # resources :dependents

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  resources :sessions

  resources :personnels do
  	resources :dependents
  end
  
  resources :positions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'personnels#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dependent.rb
class Dependent < ApplicationRecord
  belongs_to :personnel
  validates :name, :presence => true
  validates :relationship, :presence => true
end

app/models/personnel.rb
class Personnel < ApplicationRecord
  has_many :dependents, :dependent => :delete_all
  validates :name, :presence => true
  paginates_per 10

  def position_description
  	return Position.where(code: self.pos_code).first.description
  end
end

app/models/position.rb
class Position < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true,
                    uniqueness: true,
                    format: {
                      with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
                    }

  before_save :downcase_email

  def downcase_email
    self.email = email.downcase
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   private
  
  def logged_in?
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :logged_in?
end

app/controllers/dependents_controller.rb
class DependentsController < ApplicationController

   # No `new` action because form is provided by PostsController#show
  def create
    @personnel = Personnel.find(params[:personnel_id])
    # Create associated model, just like we did in the console before
    @dependent = @personnel.dependents.create(dependent_params)
    # We want to show the dependent in the context of the Post
    redirect_to @personnel
  end

  private
  def dependent_params
    params.require(:dependent).permit(:name, :relationship)
  end

end

app/controllers/personnels_controller.rb
class PersonnelsController < ApplicationController
  before_action :set_personnel, only: [:show, :edit, :update, :destroy]

  # GET /personnels
  # GET /personnels.json
  def index
    # @personnels = Personnel.all
    @personnels = Personnel.order(:name).page(params[:page])
  end

  # GET /personnels/1
  # GET /personnels/1.json
  def show
  end

  # GET /personnels/new
  def new
    @personnel = Personnel.new
  end

  # GET /personnels/1/edit
  def edit
  end

  # POST /personnels
  # POST /personnels.json
  def create
    @personnel = Personnel.new(personnel_params)

    respond_to do |format|
      if @personnel.save
        format.html { redirect_to @personnel, notice: 'Personnel was successfully created.' }
        format.json { render :show, status: :created, location: @personnel }
      else
        format.html { render :new }
        format.json { render json: @personnel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personnels/1
  # PATCH/PUT /personnels/1.json
  def update
    respond_to do |format|
      if @personnel.update(personnel_params)
        format.html { redirect_to @personnel, notice: 'Personnel was successfully updated.' }
        format.json { render :show, status: :ok, location: @personnel }
      else
        format.html { render :edit }
        format.json { render json: @personnel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personnels/1
  # DELETE /personnels/1.json
  def destroy
    @personnel.destroy
    respond_to do |format|
      format.html { redirect_to personnels_url, notice: 'Personnel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personnel
      @personnel = Personnel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personnel_params
      params.require(:personnel).permit(:name, :pos_code, :age, :about)
    end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
    # raise "edit positions"
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:code, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(allowed_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thank you for signing up!'
    else
      render :new
    end
  end
  
  private
  
  def allowed_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dependents_helper.rb
module DependentsHelper
  def valid_name(name)
    # raise "valid name!!!" if name.present? 
  end
end

app/helpers/personnels_helper.rb
module PersonnelsHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dependents/_dependent.html.erb
<div>
  <strong><%= dependent.name %> :</strong>
  <%= dependent.relationship %>
</div>

app/views/dependents/_form.html.erb
<%= form_for [@personnel, dependent] do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :relationship, "Relationship" %>
    <%= f.text_area :relationship %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dependents/edit.html.erb
<h1>Editing Dependent</h1>

<%= render 'form', dependent: @dependent %>

<%= link_to 'Show', @dependent %> |
<%= link_to 'Back', dependents_path %>

app/views/dependents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dependents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Relationship</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dependents.each do |dependent| %>
      <tr>
        <td><%= dependent.name %></td>
        <td><%= dependent.relationship %></td>
        <td><%= dependent.age %></td>
        <td><%= link_to 'Show', dependent %></td>
        <td><%= link_to 'Edit', edit_dependent_path(dependent) %></td>
        <td><%= link_to 'Destroy', dependent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dependent', new_dependent_path %>

app/views/dependents/new.html.erb
<h1>New Dependent</h1>

<%= render 'form', dependent: @dependent %>

<%= link_to 'Back', dependents_path %>

app/views/dependents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dependent.name %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @dependent.relationship %>
</p>

<p>
  <strong>Age:</strong>
  <%= @dependent.age %>
</p>

<%= link_to 'Edit', edit_dependent_path(@dependent) %> |
<%= link_to 'Back', dependents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HRMS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">

      <div id="user_header">
		 <% if logged_in? %>
		   <%= link_to 'Logout', logout_path %>
		 <% else %>
           <%= link_to "Sign Up", signup_path %>
		   <%= link_to "Log In", login_path %>		 
		 <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/personnels/_form.html.erb
<%= form_with(model: personnel, local: true) do |form| %>
  <% if personnel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(personnel.errors.count, "error") %> prohibited this personnel from being saved:</h2>

      <ul>
      <% personnel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :personnel_name %>
  </div>

  <div class="field">
    <%= form.label :pos_code %>
    <%= form.text_field :pos_code, id: :personnel_pos_code %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :personnel_age %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about, id: :personnel_about %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/personnels/edit.html.erb
<h1>Editing Personnel</h1>

<%= render 'form', personnel: @personnel %>

<%= link_to 'Show', @personnel %> |
<%= link_to 'Back', personnels_path %>

app/views/personnels/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Personnels</h1>
<%= paginate @personnels %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>About</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personnels.each do |personnel| %>
      <tr>
        <td><%= personnel.name %></td>
        <td><%= personnel.position_description %></td>
        <td><%= personnel.age %></td>
        <td><%= personnel.about %></td>
        <td><%= link_to 'Show', personnel %></td>
        <td><%= link_to 'Edit', edit_personnel_path(personnel) %></td>
        <td><%= link_to 'Destroy', personnel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @personnels %>
<br>

<%= link_to 'New Personnel', new_personnel_path %>

app/views/personnels/new.html.erb
<h1>New Personnel</h1>

<%= render 'form', personnel: @personnel %>

<%= link_to 'Back', personnels_path %>

app/views/personnels/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Employee</h1>

<p>
  <strong>Name:</strong>
  <%= @personnel.name %>
</p>

<p>
  <strong>Positon:</strong>
  <%= @personnel.position_description %>
</p>

<p>
  <strong>Age:</strong>
  <%= @personnel.age %>
</p>

<p>
  <strong>About:</strong>
  <%= @personnel.about %>
</p>

<div id="dependents">
  <h1>Dependents</h1>
  <!-- The `dependents` method returns an array-like collection, so we can call `each` on it: -->
  <% @personnel.dependents.each do |dependent| %>
    <%= render partial: "dependents/dependent", locals: {dependent: dependent} %>
  <% end %>
</div>

  <h2>Add a Dependent</h2>
  <%= render partial: "dependents/form", locals: {dependent: @personnel.dependents.new} %>


<%= link_to 'Edit', edit_personnel_path(@personnel) %> |
<%= link_to 'Back', personnels_path %>

app/views/positions/_form.html.erb
<%= form_with(model: position, local: true) do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :position_code %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :position_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Positions</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.code %></td>
        <td><%= position.description %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @position.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @position.description %>
</p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>